pages:
  image: pnavaro/jupyter
  script:
    - julia -e 'import Pkg; Pkg.add("IJulia"); Pkg.build("IJulia")'
    - pip install jupyter-book
    - make
    - jupyter-book build notebooks
    - mv notebooks/_build/html public
  tags:
    - docker
    - pages
  only:
    - master
  artifacts:
    paths:
      - public
