name: runenv
channels:
  - conda-forge
dependencies:
  - jupytext
  - pandas
  - r-irkernel
  - r-ggplot2
  - seaborn
  - scikit-learn
  - tqdm
  - pip
  - pip:
    - py-heat-magic
    - jupyter-book
