title: GitHub, Markdown and Docker
author: M2MAS AGROCAMPUS
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_extended_syntax: true

execute:
  execute_notebooks: cache

html:
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://m2mas-agrocampus.github.io/git-markdown-docker

repository:
  url: https://github.com/M2MAS-AGROCAMPUS/git-markdown-docker
  branch: master
  path_to_book: notebooks

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true
