name: jupyterbook
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install pandoc
      run: |
        sudo apt-get -yq update
        sudo apt-get install -yq pandoc texlive-xetex texlive-fonts-extra inkscape
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install Julia
      run: julia -e 'using Pkg; Pkg.add(["IJulia","Plots","StatsPlots","DataFrames"]); Pkg.build("IJulia")'
    - name: Install Miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: "latest"
          activate-environment: runenv
          environment-file: environment.yml
          auto-activate-base: false
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda run -n runenv python -m ipykernel install --user --name python3
        conda run -n runenv make
        conda run -n runenv Rscript -e 'IRkernel::installspec() ' 
    - name: Run jupyterbook
      shell: bash -l {0}
      run: conda run -n runenv jupyter-book build notebooks
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: notebooks/_build/html
